# ts.ini — настройки контейнера tarmets/tortor
# Раскомментируй нужное и перезапусти контейнер

# TS_RELEASE="latest"         # Версия TorrServer
# TS_PORT="8090"              # Порт (по умолч. 8090)
# TS_OPTIONS="-a -r"          # -a = auth, -r = read-only
# TS_UPDATE="true"            # Автообновление TorrServer
# LINUX_UPDATE="true"         # Автообновление ОС при старте

# BIP_URL="https://upd.emule-security.org/ipfilter.zip"
# BIP_URL="https://mirror.codebucket.de/transmission/blocklist.p2p.gz"

# cron_task="20 4 * * *"     # Расписание автообновлений (cron)
